### ISSUE TITLE
Bad paths in 1.2.0

### ISSUE THREAD

**Issue by andrewcsmith** [danethurber/webpack-manifest-plugin#62]
The recent minor bump was a breaking change in my setup. I'm using Rails 5.1.2, webpack-dev-server. (Fairly new to JS ecosystem tools, so bear with me...)

I have an nginx proxy set up to route all requests from www.indexical.dev/api to www.indexical.dev:9000. So the ideal routing for assets should be something like: www.indexical.dev/api/packs/application.js

I'm running webpack-dev-server with the following command:

```bash
bin/webpack-dev-server --public www.indexical.dev:9000 --inline --hot
```

And a webpacker config file like so:

```yaml
development:
  <<: *default
  public_output_path: api/packs

  dev_server:
    host: www.indexical.dev
    port: 9000
    https: false
```

All that works, except that `javascript_pack_path` in the `webpacker` gem now gives me the address `http:/www.indexical.dev/api/packs/application.js` instead of `http://www (etc)`. Somehow the change from v 1.1.2 to v 1.2.0 turned http:// into http:/, so that absolute urls were no longer possible.

Happy to answer more questions -- not exactly sure how to investigate JS issues very well, so apologies.
